# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0043_interceptionrecord_case_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.CharField(blank=True, max_length=4096)),
                ('interceptee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.Interceptee')),
            ],
        ),
    ]
